services:
  besu:
    image: hyperledger/besu:25.11.0
    container_name: besu
    network_mode: host
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xmx8g -Xms8g
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
      - 8551:8551
    volumes:
      - /root/ethereum/execution:/data
      - /root/ethereum/jwt.hex:/data/jwt.hex
    command:
      - --network=sepolia
      - --data-path=/data
      - --data-storage-format=BONSAI
      - --sync-mode=SNAP
      - --bonsai-limit-trie-logs-enabled=true
      - --bonsai-historical-block-limit=2048
      - --bonsai-trie-logs-pruning-window-size=30000
      - --rpc-http-enabled=true
      - --rpc-http-host=0.0.0.0
      - --rpc-http-port=8545
      - --rpc-http-api=ETH,NET,WEB3
      - --rpc-http-cors-origins=*
      - --host-allowlist=*
      - --rpc-http-max-active-connections=500
      - --rpc-http-max-request-content-length=52428800
      - --engine-rpc-enabled=true
      - --engine-host-allowlist=*
      - --engine-jwt-secret=/data/jwt.hex
      - --engine-rpc-port=8551
      - --nat-method=DOCKER
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  prysm:
    image: gcr.io/offchainlabs/prysm/beacon-chain:v6.1.4
    container_name: prysm
    network_mode: host
    restart: unless-stopped
    volumes:
      - /root/ethereum/consensus:/data
      - /root/ethereum/jwt.hex:/data/jwt.hex
    depends_on:
      - besu
    ports:
      - 4000:4000
      - 3500:3500
      - 13000:13000
      - 12000:12000/udp
    command:
      - --sepolia
      - --accept-terms-of-use
      - --datadir=/data
      - --disable-monitoring
      - --rpc-host=0.0.0.0
      - --execution-endpoint=http://127.0.0.1:8551
      - --jwt-secret=/data/jwt.hex
      - --rpc-port=4000
      - --grpc-gateway-corsdomain=*
      - --grpc-gateway-host=0.0.0.0
      - --grpc-gateway-port=3500
      - --min-sync-peers=3
      - --checkpoint-sync-url=https://checkpoint-sync.sepolia.ethpandaops.io
      - --genesis-beacon-api-url=https://checkpoint-sync.sepolia.ethpandaops.io
      - --p2p-tcp-port=13000
      - --p2p-udp-port=12000
      - --subscribe-all-data-subnets
      - --blob-retention-epochs=8192
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
